import { FilterSettings, PresetConfig, ViralHookSettings } from '../types';

export const DEFAULT_VIRAL_HOOK_SETTINGS: ViralHookSettings = {
  enabled: false,
  // TOP 3D HEADLINE
  showTop3DText: false,
  top3DText: 'BFF',
  top3DStyle: 'pink-neon',
  top3DSize: 46,
  top3DYPosition: 12,
  top3DDepth: 9,
  top3DRotation: -2,

  // BOTTOM VIRAL CAPTION / BRUSH BANNERS
  showBottomHook: false,

  // Line 1: Pink Grunge Brush
  line1Text: 'Awalnya biasa saja,',
  line1BgStyle: 'pink-brush',
  line1TextColor: '#ffffff',

  // Line 2: Yellow Grunge Brush
  line2Text: 'tapi ending-nya bikin penasaran banget 😳',
  line2BgStyle: 'yellow-brush',
  line2TextColor: '#000000',

  // Line 3: Script Sub-Tag
  showSubTag: false,
  subTagText: 'Ytta',
  subTagStyle: 'script-pink-wings',

  // Sizing & Margin
  bottomHookScale: 100,
  bottomHookYOffset: 5,
  bottomHookRotation: 0,
};

export const DEFAULT_FILTER_SETTINGS: FilterSettings = {
  presetId: 'original-clean',
  // 1. Logo Remover & Replacer (Default disabled until user adds a region or clicks preset)
  logoRemover: {
    enabled: false,
    regions: [],
  },

  // 2. Image Upscaling (Default: 1x Original, with 1.5x, 2x, 3x, 4x available)
  upscaleFactor: 1,
  upscaleAlgorithm: 'bicubic-sharp',

  // 3. Image Enhancement (Default: 0% clean/natural, customizable)
  enhancementClarity: 0,
  enhancementDetailSharp: 0,
  enhancementDenoise: 0,
  enhancementColorVibrance: 0,
  enhancementAutoLevel: false,

  aiHdrIntensity: 0,
  sharpness: 0,
  clarity: 0,
  aiSmoothNeural: 0,
  vibrance: 0,
  contrast: 0,
  brightness: 0,
  warmth: 0,
  bloomGlow: 0,
  vignette: 0,
  neonGlowRays: false,
  neonColor: '#ff007f',
  aspectRatio: 'original',
  fitMode: 'blur-fill',
  customCropOffsetY: 0,
  showBreakingNewsBar: false,
  breakingNewsText: 'VIRAL TERBARU HARI INI',
  breakingNewsTag: 'UPDATE',
  viralHook: DEFAULT_VIRAL_HOOK_SETTINGS,
};

export interface ViralHookTemplate {
  id: string;
  name: string;
  category: string;
  settings: Partial<ViralHookSettings>;
}

export const VIRAL_HOOK_TEMPLATES: ViralHookTemplate[] = [
  {
    id: 'bff-penasaran-ytta',
    name: '💖 BFF + Bikin Penasaran Banget (Persis Contoh)',
    category: 'Viral Trending',
    settings: {
      enabled: true,
      showTop3DText: true,
      top3DText: 'BFF',
      top3DStyle: 'pink-neon',
      top3DSize: 46,
      top3DYPosition: 12,
      top3DDepth: 9,
      top3DRotation: -2,
      showBottomHook: true,
      line1Text: 'Awalnya biasa saja,',
      line1BgStyle: 'pink-brush',
      line1TextColor: '#ffffff',
      line2Text: 'tapi ending-nya bikin penasaran banget 😳',
      line2BgStyle: 'yellow-brush',
      line2TextColor: '#000000',
      showSubTag: true,
      subTagText: 'Ytta',
      subTagStyle: 'script-pink-wings',
    },
  },
  {
    id: 'viral-slide-terakhir',
    name: '😱 VIRAL + Jangan Lihat Slide Terakhir',
    category: 'High CTR Hook',
    settings: {
      enabled: true,
      showTop3DText: true,
      top3DText: 'VIRAL',
      top3DStyle: 'fire-orange',
      top3DSize: 44,
      top3DYPosition: 12,
      top3DDepth: 9,
      top3DRotation: 0,
      showBottomHook: true,
      line1Text: 'Jangan pernah geser ke slide 2,',
      line1BgStyle: 'red-brush',
      line1TextColor: '#ffffff',
      line2Text: 'sumpah nyesel banget liat endingnya 😭',
      line2BgStyle: 'yellow-brush',
      line2TextColor: '#000000',
      showSubTag: true,
      subTagText: 'Full di Komentar 📌',
      subTagStyle: 'neon-pill',
    },
  },
  {
    id: 'asupan-salfok',
    name: '👀 ASUPAN + Pas Di-Zoom Bikin Salfok',
    category: 'Sensasi Netizen',
    settings: {
      enabled: true,
      showTop3DText: true,
      top3DText: 'ASUPAN',
      top3DStyle: 'cyan-electric',
      top3DSize: 45,
      top3DYPosition: 12,
      top3DDepth: 8,
      top3DRotation: 1,
      showBottomHook: true,
      line1Text: 'Sekilas kelihatan biasa aja,',
      line1BgStyle: 'cyan-brush',
      line1TextColor: '#ffffff',
      line2Text: 'pas di-zoom detailnya bikin salfok 🔞',
      line2BgStyle: 'yellow-brush',
      line2TextColor: '#000000',
      showSubTag: true,
      subTagText: 'Ytta',
      subTagStyle: 'script-pink-wings',
    },
  },
  {
    id: 'omg-cuma-yang-paham',
    name: '🤫 OMG + Cuma Yang Jeli Yang Paham',
    category: 'Penasaran / Komen',
    settings: {
      enabled: true,
      showTop3DText: true,
      top3DText: 'OMG',
      top3DStyle: 'purple-cyber',
      top3DSize: 42,
      top3DYPosition: 12,
      top3DDepth: 8,
      top3DRotation: -3,
      showBottomHook: true,
      line1Text: 'Cuma 1% orang yang nyadar,',
      line1BgStyle: 'pink-brush',
      line1TextColor: '#ffffff',
      line2Text: 'ada kejanggalan aneh di foto ini 🤫',
      line2BgStyle: 'white-brush',
      line2TextColor: '#000000',
      showSubTag: true,
      subTagText: 'Paham Kan? 🤔',
      subTagStyle: 'script-gold',
    },
  },
  {
    id: 'hot-5menit',
    name: '🔥 HOT + Baru Upload Udah Tembus FYP',
    category: 'Viral Trending',
    settings: {
      enabled: true,
      showTop3DText: true,
      top3DText: 'HOT',
      top3DStyle: 'gold-metal',
      top3DSize: 45,
      top3DYPosition: 12,
      top3DDepth: 10,
      top3DRotation: 0,
      showBottomHook: true,
      line1Text: 'Gak nyangka banget reaksi netizen,',
      line1BgStyle: 'dark-carbon',
      line1TextColor: '#fbbf24',
      line2Text: 'baru di-upload langsung viral se-Indonesia 🔥',
      line2BgStyle: 'yellow-brush',
      line2TextColor: '#000000',
      showSubTag: true,
      subTagText: 'Viral Indo 🇮🇩',
      subTagStyle: 'verified-badge',
    },
  },
];

export const PRESET_CONFIGS: PresetConfig[] = [
  {
    id: 'original-clean',
    name: '🌿 Original Asli (Tanpa Efek AI)',
    tagline: 'Warna & ketajaman asli foto 100% natural tanpa peningkatan filter AI.',
    description: 'Gunakan mode ini jika ingin mempertahankan foto asli apa adanya tanpa manipulasi warna atau filter AI.',
    iconName: 'Image',
    settings: {
      aiHdrIntensity: 0,
      sharpness: 0,
      clarity: 0,
      aiSmoothNeural: 0,
      vibrance: 0,
      contrast: 0,
      brightness: 0,
      warmth: 0,
      bloomGlow: 0,
      vignette: 0,
      neonGlowRays: false,
      neonColor: '#ff007f',
      aspectRatio: 'original',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'ai-masterpiece',
    name: '🌟 Ultra AI Masterpiece (Midjourney 8K HDR)',
    tagline: 'Hasil super jernih, tajam kristal, pencahayaan 3D bercahaya & warna memukau seperti buatan AI profesional.',
    description: 'Menggabungkan AI Neural Polish (kulit mulus bebas noise), Unsharp Masking 8K (mata & detail mikro super tajam), dan tone mapping S-Curve untuk kualitas gambar kelas atas.',
    iconName: 'Sparkles',
    settings: {
      aiHdrIntensity: 75,
      sharpness: 75,
      clarity: 70,
      aiSmoothNeural: 45,
      vibrance: 65,
      contrast: 42,
      brightness: 8,
      warmth: 10,
      bloomGlow: 35,
      vignette: 45,
      neonGlowRays: true,
      neonColor: '#ff007f',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'ai-3d-pixar',
    name: '🎨 3D Pixar / Octane Render Style',
    tagline: 'Gaya karakter 3D animasi modern: kulit halus berkilau, pantulan cahaya specular & warna cerah hidup.',
    description: 'Memberikan tekstur porcelain halus dan pantulan cahaya volumetrik khas render studio 3D Disney/Pixar.',
    iconName: 'Palette',
    settings: {
      aiHdrIntensity: 85,
      sharpness: 65,
      clarity: 80,
      aiSmoothNeural: 65,
      vibrance: 85,
      contrast: 48,
      brightness: 14,
      warmth: 6,
      bloomGlow: 50,
      vignette: 35,
      neonGlowRays: true,
      neonColor: '#ec4899',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'ai-hyper-real',
    name: '📸 Hyper-Realistic 8K AI Photo (Crystal Clear)',
    tagline: 'Ketajaman mikro tingkat tinggi seperti kamera format medium Hasselblad 100MP.',
    description: 'Menonjolkan detail mata, helai rambut, pori-pori dan tekstur tanpa efek berlebihan. Sangat jernih dan nyata.',
    iconName: 'Camera',
    settings: {
      aiHdrIntensity: 60,
      sharpness: 90,
      clarity: 85,
      aiSmoothNeural: 30,
      vibrance: 50,
      contrast: 40,
      brightness: 6,
      warmth: 8,
      bloomGlow: 18,
      vignette: 40,
      neonGlowRays: false,
      neonColor: '#3b82f6',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'ai-viral-hdr',
    name: '⚡ AI Viral 3D Pop & Neon Flare (Stop-Thumb FB)',
    tagline: 'Kontras punchy penghenti scroll feed Facebook dengan aksen laser glow & 3D depth.',
    description: 'Algoritma feed menyukai kontras tinggi dan highlight dramatis agar audiens langsung berhenti scroll.',
    iconName: 'Zap',
    settings: {
      aiHdrIntensity: 85,
      sharpness: 80,
      clarity: 75,
      aiSmoothNeural: 40,
      vibrance: 75,
      contrast: 50,
      brightness: 10,
      warmth: 14,
      bloomGlow: 45,
      vignette: 55,
      neonGlowRays: true,
      neonColor: '#ff007f',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'cinematic-hyper-real',
    name: '🎬 AI Cinematic Cyber Radiance 8K',
    tagline: 'Pencahayaan dramatis ala film bioskop Hollywood dengan bayangan dalam & highlight bercahaya.',
    description: 'Gradasi sinematik dengan tone hangat pada subjek dan kontras tinggi pada background.',
    iconName: 'Film',
    settings: {
      aiHdrIntensity: 75,
      sharpness: 85,
      clarity: 75,
      aiSmoothNeural: 40,
      vibrance: 55,
      contrast: 55,
      brightness: 4,
      warmth: 18,
      bloomGlow: 30,
      vignette: 60,
      neonGlowRays: true,
      neonColor: '#00f0ff',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'studio-portrait-polish',
    name: '✨ AI Porcelain Skin & Glow Portrait',
    tagline: 'Wajah glowing halus natural, mata berbinar jernih & pencahayaan studio kecantikan.',
    description: 'Sangat ideal untuk foto portrait, model, atau selfie agar terlihat mulus sempurna seperti editan AI beauty.',
    iconName: 'Sparkles',
    settings: {
      aiHdrIntensity: 55,
      sharpness: 70,
      clarity: 60,
      aiSmoothNeural: 70,
      vibrance: 45,
      contrast: 32,
      brightness: 12,
      warmth: 10,
      bloomGlow: 40,
      vignette: 25,
      neonGlowRays: false,
      neonColor: '#f43f5e',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'anime-vibrant-glow',
    name: '🌌 AI Anime Sky & Celestial Art (Shinkai HDR)',
    tagline: 'Warna langit dan pemandangan vibran menyala seperti anime layar lebar Makoto Shinkai.',
    description: 'Meningkatkan saturasi warna biru, magenta, dan pencahayaan langit menjadi sangat indah dan memukau.',
    iconName: 'Palette',
    settings: {
      aiHdrIntensity: 80,
      sharpness: 65,
      clarity: 70,
      aiSmoothNeural: 50,
      vibrance: 95,
      contrast: 40,
      brightness: 15,
      warmth: -4,
      bloomGlow: 65,
      vignette: 30,
      neonGlowRays: true,
      neonColor: '#a855f7',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
  {
    id: 'ultra-sharp-clarity',
    name: '🔍 8K AI Super-Resolution De-Blur',
    tagline: 'Maksimum ketajaman & pemulihan detail untuk foto yang buram, pecah, atau kurang fokus.',
    description: 'Menarik detail mikro garis dan tekstur agar gambar menjadi super jelas dan tajam saat diperbesar.',
    iconName: 'Zap',
    settings: {
      aiHdrIntensity: 70,
      sharpness: 100,
      clarity: 100,
      aiSmoothNeural: 20,
      vibrance: 45,
      contrast: 45,
      brightness: 6,
      warmth: 4,
      bloomGlow: 15,
      vignette: 35,
      neonGlowRays: false,
      neonColor: '#10b981',
      aspectRatio: '4:5',
      fitMode: 'blur-fill',
    },
  },
];
